default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

stages:
  - check
  - test
  - build
  - bump
  - docker-bump
  - release
#  - deploy

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  # DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_BACKEND_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/backend
  CONTAINER_FRONTEND_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/frontend
  CONTAINER_VARNISH_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/varnish
  VERSION_NUMBER: 1

check-backend:
  stage: check
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common git
  script:
    - cd backend
    - make check
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


# check-frontend:
#   image: node:20-alpine
#   stage: check
#   before_script:
#     - apk add --no-cache make bash python3 ncurses openssh-client-common git
#     - corepack enable
#   script:
#     - cd frontend
#     - make install
#     - make lint
#     - make ci-i18n
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'



test-backend:
  stage: test
  image: python:3.11-bookworm
  before_script:
    - apt update
    - apt install build-essential python3 python3-dev git -y
  script:
    - cd backend
    - make install
    - make test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

test-frontend:
  image: node:20-alpine
  stage: test
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common git
    - corepack enable

  script:
    - cd frontend
    - make install
    - make test-ci
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


test-build-backend:
  stage: build
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common
  script:
    - cd backend
    - make build-image
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push $CONTAINER_BACKEND_RELEASE_IMAGE:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

test-build-frontend:
  stage: build
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common

  script:
    - cd frontend
    - make build-image
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker push $CONTAINER_FRONTEND_RELEASE_IMAGE:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

bump-version:
  image: node:20-alpine
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  stage: bump
  before_script:
    # install basic packages
    - apk add --no-cache make bash python3 ncurses openssh-client openssh-client-common git
    # Git dance
    - eval `ssh-agent -s`
    - echo "${VOLTO_DEPLOY_SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
    # create ssh configuration to disable host checking when pushing
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/config
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Configure git
    - git config --global user.name "${CI_GITLAB_USERNAME}"
    - git config --global user.email "${CI_GITLAB_USER_EMAIL}"
    # Get git repo URL using ssh syntax
    - export CI_PUSH_REPO=$(echo "$CI_REPOSITORY_URL" | sed -e "s|.*@\(.*\)|git@\1|" -e "s|/|:/|" )
    - git remote set-url --push origin "ssh://${CI_PUSH_REPO}"
    - git checkout -B $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME
    - git push origin -u $CI_COMMIT_REF_NAME
  script:
    # Install npm required packages
    - npm i -D @release-it/conventional-changelog @release-it/bumper
    - npx release-it -y --ci
    # - git push origin $CI_COMMIT_REF_NAME -u -o ci.skip

bump-docker-compose-version:
  stage: docker-bump
  before_script:
    # install basic packages
    - apk add --no-cache make bash python3 ncurses openssh-client openssh-client-common git
    # Login in container registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    # Git dance
    - eval `ssh-agent -s`
    - echo "${VOLTO_DEPLOY_SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
    # create ssh configuration to disable host checking when pushing
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/config
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Configure git
    - git config --global user.name "${CI_GITLAB_USERNAME}"
    - git config --global user.email "${CI_GITLAB_USER_EMAIL}"
    # Get git repo URL using ssh syntax
    - export CI_PUSH_REPO=$(echo "$CI_REPOSITORY_URL" | sed -e "s|.*@\(.*\)|git@\1|" -e "s|/|:/|" )
    - git remote set-url --push origin "ssh://${CI_PUSH_REPO}"
    - git checkout -B $CI_COMMIT_REF_NAME
    - git pull origin $CI_COMMIT_REF_NAME
    - git push origin -u $CI_COMMIT_REF_NAME

  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull registry.gitlab.com/codesyntax/deploy-helpers:latest
    - docker run -v $(pwd):/app registry.gitlab.com/codesyntax/deploy-helpers:latest ./plone_project_docker_images_bump.py
    - git add deploy
    - git commit -m "bump version [ci skip]"
    - git push origin $CI_COMMIT_REF_NAME

build-and-release-backend:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  stage: release
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client openssh-client-common
    - export VERSION_NUMBER=$(cat version.txt)
  script:
    - cd backend
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $CONTAINER_BACKEND_RELEASE_IMAGE:latest
    - docker tag $CONTAINER_BACKEND_RELEASE_IMAGE:latest $CONTAINER_BACKEND_RELEASE_IMAGE:$VERSION_NUMBER
    - docker push $CONTAINER_BACKEND_RELEASE_IMAGE:$VERSION_NUMBER

build-and-release-frontend:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  stage: release
  before_script:
    - apk add --no-cache make bash python3 ncurses openssh-client-common
    - export VERSION_NUMBER=$(cat version.txt)

  script:
    - cd frontend
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker pull $CONTAINER_FRONTEND_RELEASE_IMAGE:latest
    - docker tag $CONTAINER_FRONTEND_RELEASE_IMAGE:latest $CONTAINER_FRONTEND_RELEASE_IMAGE:$VERSION_NUMBER
    - docker push $CONTAINER_FRONTEND_RELEASE_IMAGE:$VERSION_NUMBER

# deploy:
#   stage: deploy
#   rules:
#     - if: $CI_COMMIT_TAG
#   script:
#     - mkdir -p ~/.ssh/
#     - touch ~/.ssh/known_hosts
#     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#     - cd devops
#     - eval `ssh-agent -s`
#     - echo "${DEPLOY_SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null # add ssh key
#     - export TERM=dumb
#     - export VERSION_NUMBER=$(cat version.txt)
#     - touch .env
#     - 'echo "DEPLOY_ENV=${DEPLOY_ENV}" >> .env'
#     - 'echo "DEPLOY_HOST=${DEPLOY_HOST}" >> .env'
#     - 'echo "DEPLOY_PORT=${DEPLOY_PORT}" >> .env'
#     - 'echo "DEPLOY_USER=${DEPLOY_USER}" >> .env'
#     - 'echo "DOCKER_CONFIG=${DOCKER_CONFIG}" >> .env'
#     - 'echo "STACK_NAME=${STACK_NAME}" >> .env'
#     - 'echo "STACK_PARAM=${VERSION_NUMBER}" >> .env'
#     # Force using the environment variables, because .env file contents are not taken by docker stack deploy
#     - export $(cat .env)
#     - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#     - make docker-setup
#     - make stack-deploy
#   environment: production
# deploy-with-auxiliary-docker-image:
#   stage: deploy
#   variables:
#     REGISTRY: ${CI_REGISTRY}
#     USERNAME: ${CI_REGISTRY_USER}
#     PASSWORD: ${CI_REGISTRY_PASSWORD}
#     REMOTE_HOST: ${DEPLOY_HOST}
#     REMOTE_PORT: ${DEPLOY_PORT}
#     REMOTE_USER: ${DEPLOY_USER}
#     REMOTE_PRIVATE_KEY: "${DEPLOY_SSH_PRIVATE_KEY}"
#     STACK_FILE: devops/stacks/${DEPLOY_HOST}.yml
#     STACK_NAME: ${STACK_NAME}
#     DEPLOY_IMAGE: ghcr.io/kitconcept/docker-stack-deploy:latest
#   script:
#     - docker pull ${DEPLOY_IMAGE}
#     - docker run --rm
#       -v "$(pwd)":/github/workspace
#       -v /var/run/docker.sock:/var/run/docker.sock
#       -e REGISTRY=${REGISTRY}
#       -e USERNAME=${USERNAME}
#       -e PASSWORD=${PASSWORD}
#       -e REMOTE_HOST=${REMOTE_HOST}
#       -e REMOTE_PORT=${REMOTE_PORT}
#       -e REMOTE_USER=${REMOTE_USER}
#       -e REMOTE_PRIVATE_KEY="${REMOTE_PRIVATE_KEY}"
#       -e STACK_FILE=${STACK_FILE}
#       -e STACK_NAME=${STACK_NAME}
#       ${DEPLOY_IMAGE}
#   only:
#     - main
#   environment: production
