services:
  backend:
    depends_on:
    - db
    environment:
      RELSTORAGE_DSN: dbname='${DB_NAME:-plone}' user='${DB_USER:-plone}' host='${DB_HOST:-db}'
        password='${DB_PASSWORD:-CTBolRnPQVoh}' port='${DB_PORT:-5432}'
    healthcheck:
      interval: 40s
      retries: 3
      start_period: 60s
      test: curl --fail http://localhost:8080/Plone/ok || exit 1
      timeout: 30s
    image: registry.gitlab.com/codesyntax/deporeibar-baietz-312/backend:1.0.16
    ports:
    - 8080:8080
  caddy:
    image: caddy
    ports:
    - 80:80
    - 443:443
    - 443:443/udp
    volumes:
    - ./conf/Caddyfile:/etc/caddy/Caddyfile
    - caddy_data:/data
    - caddy_config:/config
  db:
    deploy: {}
    environment:
      POSTGRES_DB: plone
      POSTGRES_PASSWORD: CTBolRnPQVoh
      POSTGRES_USER: plone
    image: postgres:14
    volumes:
    - ./data/db:/var/lib/postgresql/data
  frontend:
    depends_on:
    - backend
    environment:
      RAZZLE_API_PATH: https://test.312.deporeibar.com
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    healthcheck:
      interval: 40s
      retries: 3
      start_period: 60s
      test: curl --fail http://localhost:3000/Plone/ok || exit 1
      timeout: 30s
    image: registry.gitlab.com/codesyntax/deporeibar-baietz-312/frontend:1.0.16
  nginx:
    depends_on:
    - backend
    - frontend
    environment:
      SERVER_DOMAIN: test.312.deporeibar.com
    image: nginx
    volumes:
    - ./conf/default.conf.template:/etc/nginx/templates/default.conf.template
    - ./conf/dhparam.pem:/etc/nginx/ssl/dhparam.pem
version: '3.8'
volumes:
  caddy_config: null
  caddy_data: null
  vol-certbot-certs:
    driver_opts:
      device: ./data/certbot/conf/
      o: bind
      type: none
  vol-certbot-www:
    driver_opts:
      device: ./data/certbot/www/
      o: bind
      type: none
  vol-site-data:
    driver_opts:
      device: ./data/db/
      o: bind
      type: none
